"""Piaozone's BASE64 / Sun SHA1PRNG-derived AES-GCM wire encoding."""
import base64
import hashlib
import os
from decimal import Decimal

import simplejson
from cryptography.hazmat.primitives.ciphers.aead import AESGCM

from .exceptions import ProtocolError


def dumps(value):
    def check(item):
        if isinstance(item, Decimal) and not item.is_finite():
            raise ValueError('Non-finite decimal in Piaozone payload.')
        if isinstance(item, dict):
            for child in item.values():
                check(child)
        elif isinstance(item, (list, tuple)):
            for child in item:
                check(child)
    check(value)
    return simplejson.dumps(value, ensure_ascii=False, use_decimal=True, allow_nan=False,
                            separators=(",", ":"))


class Codec:
    def __init__(self, mode="base64", password=None):
        if mode not in ("base64", "aes") or (mode == "aes" and not password):
            raise ValueError("Choose base64 or aes with an encryption password.")
        self.mode = mode
        # First 16 bytes generated by Sun SHA1PRNG when seeded before first use.
        self._key = hashlib.sha1(hashlib.sha1(password.encode("utf-8")).digest()).digest()[:16] if password else None

    def encode(self, value):
        raw = dumps(value).encode("utf-8")
        if self.mode == "aes":
            nonce = os.urandom(12)
            raw = nonce + AESGCM(self._key).encrypt(nonce, raw, None)
        return base64.b64encode(raw).decode("ascii")

    def decode(self, value):
        if not isinstance(value, str):
            raise ProtocolError("Expected an encoded Piaozone response.")
        try:
            raw = base64.b64decode(value, validate=True)
            if self.mode == "aes":
                raw = AESGCM(self._key).decrypt(raw[:12], raw[12:], None)
            return simplejson.loads(raw.decode("utf-8"), use_decimal=True, allow_nan=False)
        except Exception:
            raise ProtocolError("Invalid Piaozone response encoding or authentication tag.") from None
